version: '2.1'

services:
  ihatemoney:
    build: .
    environment:
      - SQLITE_DATABASE=/var/lib/ihatemoney/ihatemoney.sqlite
      - ACTIVATE_DEMO_PROJECT=False
      - ADMIN_PASSWORD=pbkdf2:sha256:260000$DxG96nzhVO2znqMo$89b6f4b287f4557bca0993a83d24375888d2ad805d57f53687122fa83feaa9b9
      - ALLOW_PUBLIC_PROJECT_CREATION=True
      - ACTIVATE_ADMIN_DASHBOARD=True
    volumes:
      - /mnt/mydatastorage/ihatemoney-storage:/var/lib/ihatemoney
    ports:
      - 80:80
    restart: unless-stopped
  ihatemoney_edits:
    build: ./edits
    environment:
      - SQLITE_DATABASE=/var/lib/ihatemoney/ihatemoney.sqlite
    volumes:
      - ./storage:/var/lib/ihatemoney
    ports:
      - 8081:80
    restart: unless-stopped